name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: TypeScript type checking - Server
      run: npm run typecheck --workspace=server

    - name: TypeScript type checking - Client
      run: |
        cd client
        npx tsc -b

    - name: ESLint - Client
      run: npm run lint --workspace=client

    - name: Build - Server
      run: npm run build --workspace=server

    - name: Build - Client
      run: npm run build --workspace=client

    - name: Run tests - Server
      run: npm run test --workspace=server
      env:
        NODE_OPTIONS: '--experimental-vm-modules'

    - name: Upload test coverage
      uses: codecov/codecov-action@v3
      if: matrix.node-version == '20.x'
      with:
        file: ./server/coverage/lcov.info
        flags: server
        name: server-coverage
        fail_ci_if_error: false

  security:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run security audit
      run: npm audit --audit-level=moderate

    - name: Check for security vulnerabilities in workspaces
      run: |
        npm audit --workspace=client --audit-level=moderate
        npm audit --workspace=server --audit-level=moderate

  lint-and-format:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Check for trailing whitespace
      run: |
        if npm run whitespace --dry-run 2>/dev/null; then
          echo "Running whitespace check in dry-run mode"
          # Check if whitespace script would make changes
          git diff --exit-code || (echo "Trailing whitespace found. Run 'npm run whitespace' to fix." && exit 1)
        else
          echo "Whitespace script not available or doesn't support dry-run"
        fi

  dependency-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Verify lockfile integrity
      run: npm ci --ignore-scripts

    - name: Check for outdated dependencies
      run: |
        echo "Checking for outdated dependencies..."
        npm outdated --workspace=client || true
        npm outdated --workspace=server || true
        echo "Outdated check completed (non-blocking)"